[workspace]
authors = ["landonmmcfarland1 <landon.m.mcfarland@gmail.com>"]
channels = ["conda-forge"]
name = "regression-practice"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
marimo = ">=0.19.2,<0.20"
polars = ">=1.37.1,<2"
pyarrow = ">=22.0.0,<23"
spyder = ">=6.1.2,<7"
duckdb = ">=1.4.3,<2"
numpy = ">=2.4.1,<3"
sqlglot = ">=28.5.0,<29"
